/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "main.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    /* Loop forever */
	RCC_AHB1ENR_t *RCC_AHB1ENR = (RCC_AHB1ENR_t*)(0x40023800 + 0x30);
	GPIOx_MODER_t *GPIOD_MODER = (GPIOx_MODER_t*)(0x40020C00);
	GPIOx_ODR_t   *GPIOD_ODR   = (GPIOx_ODR_t*)  (0x40020C00 + 0x14);

	// Enable GPIOD
	RCC_AHB1ENR->GPIODEN = 1;

	// PD15 = Blue User LED
	GPIOD_MODER->MODER15 = 0b01; // Output Mode
	GPIOD_ODR->ODR15 = 1;

	while (1)
	{
		for(int volatile i = 0; i<500000; ++i);
		GPIOD_ODR->ODR15 ^= 1;

	};
}
